-- insert records into Sales.Categories 

INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Beverages', 'Soft drinks, coffees, teas, beers, and ales');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Confections', 'Desserts, candies, and sweet breads');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Dairy Products', 'Cheeses');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Grains/Cereals', 'Breads, crackers, pasta, and cereal');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Meat/Poultry', 'Prepared meats');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Produce', 'Dried fruit and bean curd');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Seafood', 'Seaweed and fish');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Snacks', 'Chips, pretzels, and snack foods');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Soups', 'Bouillons, and consomm�s');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Baked Goods', 'Cookies, cakes, and pastries');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Pasta', 'Noodles, macaroni, and spaghetti');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Frozen Foods', 'Frozen vegetables, fruits, and meals');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Beverages', 'Juices and bottled water');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Condiments', 'Mustards, ketchups, and salad dressings');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Confections', 'Chocolate, candy bars, and gum');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Dairy Products', 'Milk, yogurt, and butter');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Grains/Cereals', 'Rice, oats, and barley');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Meat/Poultry', 'Chicken, turkey, and beef');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Produce', 'Fresh fruits and vegetables');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Seafood', 'Shrimp, crab, and lobster');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Snacks', 'Popcorn, nuts, and trail mix');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Soups', 'Ready-to-eat soups and stews');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Baked Goods', 'Bread, rolls, and muffins');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Pasta', 'Penne, fettuccine, and ravioli');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Frozen Foods', 'Frozen pizzas, pies, and snacks');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Beverages', 'Alcoholic beverages and mixers');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Condiments', 'Mayonnaise, vinegar, and marinades');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Confections', 'Ice cream, sherbet, and sorbet');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Dairy Products', 'Cream, sour cream, and cheese');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Non-Alcoholic Beverages', 'Soft drinks, juices, and energy drinks');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Gourmet Foods', 'Specialty and high-quality food items');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Organic Foods', 'Organic fruits, vegetables, and meats');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Pet Foods', 'Food products for pets like dogs and cats');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Baby Foods', 'Food products specifically made for infants and toddlers');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Canned Goods', 'Canned fruits, vegetables, and soups');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Baking Supplies', 'Flour, sugar, baking powder, and other baking ingredients');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Spices and Herbs', 'Dried spices, herbs, and seasonings');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Breakfast Foods', 'Cereals, pancake mixes, and breakfast bars');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Deli Foods', 'Prepared deli meats, cheeses, and salads');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Grilling Supplies', 'Barbecue sauces, charcoal, and grilling tools');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Healthy Snacks', 'Low-fat, low-sugar, and organic snacks');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Ethnic Foods', 'Specialty foods from various cultures and regions');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Prepared Meals', 'Ready-to-eat meals and microwave dinners');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Energy Foods', 'High-energy foods like protein bars and shakes');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Cereal Products', 'Breakfast cereals and granola products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Cheese', 'Various types of cheese and cheese products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Coffee and Tea', 'Different types of coffee, tea, and accessories');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Gourmet Snacks', 'Premium quality snack items');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Instant Foods', 'Instant noodles, soups, and meals');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Protein Foods', 'High-protein foods for athletes and fitness enthusiasts');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Diet Foods', 'Diet-friendly foods and low-calorie options');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Fresh Foods', 'Fresh produce, dairy, and meat products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Pantry Essentials', 'Basic pantry items like pasta, rice, and canned beans');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Specialty Meats', 'Unique and specialty meat products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Seafood Delicacies', 'Special seafood items like caviar and smoked salmon');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Luxury Foods', 'High-end and luxury food products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Cooking Oils', 'Various types of cooking oils and fats');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Sauces and Dressings', 'Variety of sauces, dressings, and marinades');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Poultry', 'Chicken, turkey, and other poultry products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Condiments', 'Honey, mustard, ketchup, and other condiments');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Canned Seafood', 'Canned tuna, salmon, and other seafood');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Frozen Desserts', 'Ice cream, frozen yogurt, and sorbet');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Gluten-Free Foods', 'Products made without gluten for dietary needs');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Low-Sodium Foods', 'Foods with reduced salt content');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Vegan Foods', 'Plant-based food products suitable for vegans');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Non-Dairy Beverages', 'Milk alternatives like almond, soy, and oat milk');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Nut Butters', 'Peanut butter, almond butter, and other nut spreads');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Pickled Products', 'Pickles, olives, and other pickled items');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Snack Bars', 'Granola bars, protein bars, and snack bars');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Trail Mixes', 'Mixed nuts, dried fruits, and other trail mix items');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Dried Fruits', 'Dried apricots, raisins, and other dried fruits');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Frozen Vegetables', 'Frozen peas, carrots, and other vegetables');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Cooking Wine', 'Wines specifically made for cooking');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Herbal Teas', 'Variety of caffeine-free herbal teas');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Baking Mixes', 'Cake mixes, muffin mixes, and other baking mixes');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Gourmet Cheeses', 'Artisan and gourmet cheese varieties');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Canned Soups', 'Ready-to-eat canned soups');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Specialty Oils', 'Olive oil, coconut oil, and other specialty oils');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Healthy Beverages', 'Kombucha, detox drinks, and other healthy beverages');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Organic Snacks', 'Organic chips, crackers, and other snacks');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Ready-to-Eat Meals', 'Convenient, pre-packaged meals');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Artisan Breads', 'Handcrafted, artisan bread varieties');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Cheese Alternatives', 'Non-dairy cheese products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Breakfast Pastries', 'Croissants, danishes, and other pastries');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Marinades', 'Various marinades for meats and vegetables');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Plant-Based Meats', 'Meat alternatives made from plants');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Smoothie Ingredients', 'Frozen fruits, yogurt, and other smoothie ingredients');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Soy Products', 'Tofu, tempeh, and other soy-based products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Energy Drinks', 'Caffeinated and non-caffeinated energy drinks');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Organic Vegetables', 'Certified organic fresh vegetables');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Canned Meats', 'Canned beef, chicken, and other meats');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Dried Meats', 'Jerky, dried sausage, and other dried meat products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Frozen Snacks', 'Frozen appetizers and snack foods');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('International Foods', 'Specialty foods from various countries');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Holiday Foods', 'Seasonal foods for holidays and special occasions');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Sugar-Free Foods', 'Foods made without added sugars');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Low-Fat Foods', 'Foods with reduced fat content');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Kosher Foods', 'Foods prepared in accordance with Jewish dietary laws');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Halal Foods', 'Foods prepared in accordance with Islamic dietary laws');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Organic Dairy', 'Organic milk, cheese, and other dairy products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Ethnic Spices', 'Spices and seasonings from different ethnic cuisines');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Fruit Juices', 'Various types of fruit juices and blends');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Vegetable Juices', 'Various types of vegetable juices and blends');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Smoothies', 'Pre-made and ready-to-blend smoothies');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Cereal Bars', 'Breakfast bars made from cereal grains');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Sports Drinks', 'Beverages designed for athletes and active individuals');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Protein Shakes', 'Ready-to-drink protein beverages');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Nutritious Foods', 'Foods designed for balanced nutrition');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Instant Breakfast', 'Instant breakfast drinks and mixes');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Snack Cakes', 'Packaged snack cakes and desserts');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Cheese Snacks', 'Cheese sticks, slices, and other cheese snacks');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Dried Seafood', 'Dried fish, squid, and other seafood');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Condensed Milk', 'Sweetened condensed milk and evaporated milk');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Butter and Margarine', 'Various types of butter and margarine');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Yogurt', 'Different types of yogurt and yogurt products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Syrups', 'Maple syrup, pancake syrup, and other syrups');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Frozen Berries', 'Assorted frozen berry products');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Baby Formula', 'Various types of baby formula');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Baby Snacks', 'Snacks specifically designed for babies and toddlers');
INSERT INTO Sales.Categories (CategoryName, Description) VALUES ('Meal Kits', 'Pre-packaged meal kits with ingredients and recipes');
