-- Inserting sample records into the Sales.Region table

INSERT INTO Sales.Region (RegionDescription) VALUES
('Eastern'),
('Western'),
('Northern'),
('Southern'),
('Central'),
('Northeast'),
('Southeast'),
('Northwest'),
('Southwest'),
('Midwest'),
('New England'),
('Deep South'),
('Mid-Atlantic'),
('Great Lakes'),
('South Central'),
('Pacific Northwest'),
('Rocky Mountains'),
('Gulf Coast'),
('Appalachia'),
('Plains'),
('Upper Midwest'),
('Sun Belt'),
('Four Corners'),
('Northern Rockies'),
('Southwest Desert'),
('Southeast Coast'),
('Tidewater'),
('Down East'),
('Northern California'),
('Southern California'),
('Central Valley'),
('Gold Country'),
('Bay Area'),
('Inland Empire'),
('San Francisco Bay Area'),
('Silicon Valley'),
('Central Coast'),
('North Bay'),
('Wine Country'),
('Los Angeles Metropolitan Area'),
('San Diego Metropolitan Area'),
('Sacramento Metropolitan Area'),
('Santa Cruz Metropolitan Area'),
('Fresno Metropolitan Area'),
('Bakersfield Metropolitan Area'),
('Stockton Metropolitan Area'),
('Chico Metropolitan Area'),
('Visalia Metropolitan Area'),
('Modesto Metropolitan Area'),
('Redding Metropolitan Area'),
('Riverside-San Bernardino Metropolitan Area'),
('Santa Barbara Metropolitan Area'),
('Salinas Metropolitan Area'),
('Ventura Metropolitan Area'),
('Oxnard Metropolitan Area'),
('Oakland Metropolitan Area'),
('Riverside Metropolitan Area'),
('San Bernardino Metropolitan Area'),
('San Luis Obispo Metropolitan Area'),
('Santa Rosa Metropolitan Area'),
('Vallejo Metropolitan Area'),
('Fairfield Metropolitan Area'),
('Santa Maria Metropolitan Area'),
('Yuba City Metropolitan Area'),
('San Jose Metropolitan Area'),
('Napa Metropolitan Area'),
('Merced Metropolitan Area'),
('Santa Cruz-Watsonville Metropolitan Area'),
('Hanford-Corcoran Metropolitan Area'),
('Madera Metropolitan Area'),
('Yuba City Metropolitan Area'),
('San Francisco Metropolitan Area'),
('Santa Barbara-Santa Maria-Goleta Metropolitan Area'),
('Modesto Metropolitan Area'),
('Palm Springs Metropolitan Area'),
('Visalia-Porterville Metropolitan Area'),
('Bakersfield Metropolitan Area'),
('San Diego-Carlsbad Metropolitan Area'),
('San Jose-Sunnyvale-Santa Clara Metropolitan Area'),
('Redding Metropolitan Area'),
('Salinas Metropolitan Area'),
('Los Angeles-Long Beach-Glendale Metropolitan Area'),
('Fresno Metropolitan Area'),
('Riverside-San Bernardino-Ontario Metropolitan Area'),
('Stockton-Lodi Metropolitan Area'),
('Oxnard-Thousand Oaks-Ventura Metropolitan Area'),
('Santa Rosa-Petaluma Metropolitan Area'),
('Vallejo-Fairfield Metropolitan Area'),
('Merced Metropolitan Area'),
('Napa Metropolitan Area'),
('Chico Metropolitan Area'),
('El Centro Metropolitan Area'),
('Lake Tahoe Metropolitan Area'),
('Santa Maria-Santa Barbara Metropolitan Area'),
('Yuba City Metropolitan Area'),
('Hanford-Corcoran Metropolitan Area'),
('Visalia-Porterville Metropolitan Area'),
('Madera Metropolitan Area'),
('Merced Metropolitan Area'),
('Yuba City Metropolitan Area'),
('Hanford-Corcoran Metropolitan Area'),
('Visalia-Porterville Metropolitan Area'),
('Madera Metropolitan Area'),
('Bend Metropolitan Area'),
('Yakima Metropolitan Area'),
('Medford Metropolitan Area'),
('Corvallis Metropolitan Area'),
('Bellingham Metropolitan Area'),
('Longview Metropolitan Area'),
('Olympia Metropolitan Area'),
('Bremerton Metropolitan Area'),
('Walla Walla Metropolitan Area'),
('Richland Metropolitan Area'),
('Pullman Metropolitan Area'),
('Ellensburg Metropolitan Area'),
('Mount Vernon Metropolitan Area'),
('Wenatchee Metropolitan Area'),
('Moses Lake Metropolitan Area'),
('Port Angeles Metropolitan Area'),
('Oak Harbor Metropolitan Area'),
('Anacortes Metropolitan Area'),
('Centralia Metropolitan Area'),
('Aberdeen Metropolitan Area'),
('Bellingham Metropolitan Area'),
('Bremerton Metropolitan Area'),
('Centralia Metropolitan Area'),
('Ellensburg Metropolitan Area'),
('Longview Metropolitan Area'),
('Mount Vernon Metropolitan Area'),
('Oak Harbor Metropolitan Area'),
('Olympia Metropolitan Area'),
('Port Angeles Metropolitan Area'),
('Pullman Metropolitan Area'),
('Walla Walla Metropolitan Area'),
('Wenatchee Metropolitan Area'),
('Yakima Metropolitan Area'),
('Moses Lake Metropolitan Area'),
('Anacortes Metropolitan Area'),
('Aberdeen Metropolitan Area'),
('Medford Metropolitan Area'),
('Bend Metropolitan Area'),
('Corvallis Metropolitan Area');
